version: '3.8'

networks:
  corp:
    driver: bridge

services:
  api-server:
    container_name: api-server
    build:
      context: ./
      cache_from:
        - user-app-base-image:nx-base
      dockerfile: ./apps/user-app-server/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: api-server:nx-dev
    ports:
      - 4939:4939
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      NODE_ENV: 'development'
      PORT: 4939
      MONGO_SERVER_URL: 'mongo'
    networks:
      - corp
    restart: on-failure
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - corp
  react-client:
    container_name: react-client
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/user-app/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: react-client:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'development'
      PORT: 4900
    networks:
      - corp
    restart: on-failure
